### ISSUE TITLE
kubernetes token - request

### ISSUE THREAD

**Issue by Abdul2** [UKHomeOffice/hosting-platform#386]
Please can I have a kubernetes token with access to my teams namespaces.  
Email: abdul.abdi@digital.homeoffice.gov.uk  
Name: abdul abdi 
Team: CoE-Architecture
Public GPG Key: 
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFir24QBEADMi1WZliCNvTLZE5GT9JdcX/0wrUVB/iGRWCG0tWgeOM9wU1HP
3aMnqoM8xibHnBsYcrGGT/76AChUAiMrJ8xMYpcxerjqUexkX9fEiwXbD47aV9Yd
nhmy6XtT2LJndVg8WtrrrGReQP7ykIVAQLrorvzcYapuvA3KW+7DMHsk2au/UjRS
mnH0rv93bzt+X4D7gEjYiFB/N17I002E+rE3qG4c3eh1rMDUDpDd7sP15HCyEzSt
H3IU+NegHGByoBuS8i/n061hBC+rJh4E/St+dQJtwSaTcddExQ7eIhun7CTx5v/7
vllOufLIAJW18gxuLRnfUKJXSUuBGE1eHOfJmfQfl31mdWcf1FzQVT5kIpcqbu9s
gJBYv1aiudBZdGSlQMNzbscm8hJM99FIbAU5Pm/2YiPbz4wLi2ktxCt5DyHjkOK/
0NjFjR/NCX4Efry0mLn6czz2rWh/69+RlUqm+on5Lf/zc7Jv2zRJzDd7pjvTcOqe
RlTt4seBTr6vBmT8YviO3MgFqx+sXRzPQyeJBbnZBvdfW0Ha++/3lH+0piTLehwj
Nggk3lUgSJ41RlEyU7/35eChF5FSS91bsvkGlHgAlrvH60tj2FWRRDJUfXxRCFOb
1ar86V78apm1x1bXT01/cPEbu/lKvyFB2LRL9Mw/L4ePu+ULgTVC9WlFuQARAQAB
tDBBYmR1bCBBYmRpIChBYmR1bCBBYmRpKSA8YWJkdWxyYXNoaWQyQGdtYWlsLmNv
bT6JAj8EEwEIACkFAlir24QCGwMFCQAnjQAHCwkIBwMCAQYVCAIJCgsEFgIDAQIe
AQIXgAAKCRCb2DLMZpiBEDKMD/9FEpO2vwFly80K3jEv1yXOkq7fvDYo4CVVTcPx
euTjTqC+mmxOA7/PuYcNtDabxqWLmHXM5dqatGs/SCsfDWHuK48tYGYcCpoFDZRq
ilxBuev29LQkC6LAX90yYvGAj+TvwIWB5ncYtrVVdrgbFXprWgpRWHJM949pETuk
X8XhrbSOVQDExeDJ7JljZ/Misfs0fJf/hsDtp4fKU61biufPWSMjsotUMtMFbevK
TBgI6SXfyQfacalm7dixOdvQNc0eIZDKEcUD8CkKWgI4X2stlPBrv/Tx9XhJ5/hk
qoJ839oN7rVOhXVrPhCv1KRkdn2b3JladR68CwYxQ1LZHK7iUA+hNPOOnRZY7C/D
W4EaXbgJGaBksIQc5A9uevwZXkoiAhg/JCoNUnmsb27qPq3WRtti30zyKV/HnXj8
ggSJXPeM1MeFKAYAYeeaBXgLZTSAhifieuGK67HXPy2B9Hs0rSTZRiOAv6gipoGL
sxaMhJ1v6yeqDMQriWFN89l19cT3v8QUDc6dWdEy1MZp5dJuLO3a8atC/7pXjLzS
fJsRXf7lPoRLu7xWQEGs34ZqgRBFCxEzxHohDjniakwPNkrs1RBOVPkXhcPjCfZO
BBuRpelO2IiqfE+Q1w2Ot6yTtzuZbCNdjI9yJBiZ4XUoni/ATitrOsA4Yvle5Cu7
0TWJ5LkCDQRYq9uEARAAs5BQBMxwkeZwzfVyCJSN+bemoMexZiTJj65uduu8rgxU
b4PFRIRHnbrq6hphxMxX7IZj2A+U1BQWH6ChqiE0DUDKGI6zpsfdHf7k8QNxoMHs
zjUcm6y6WLsSawHhS3lDkfBkaDjmrnceMy3l1ZR/XkXFl51s2ea8P34sbnKytmv0
uZjSp03erRdjuNipGITUfvjsPSFs4bnvgP7dwctcy3bvMOQ49yn1TwdpyJFTlUGf
jGnod3DuPjGwK+hi0NjVl6fZRzbvvcCsyc9q1SUSCqOXfoXo6yXhUGwkuUCVU8AL
HRpLNxtpohn0nB6olObIgDvUTW6u3+gMwFiCMNW19II01pXWFh42/HJQRn74txn6
xKIx6VJKzvZjxwTZdEkLQnMVYVlYyAOROAiOrpMHnYoQo+K4jvXOV26nuOktYr1g
AoE7kuG/0OxnOjZwggx8oQ/fNCXwU2y/FKOyQi5uBRMB5THuO7TLfAQSP6T51wfd
6C+Hh5tYaVJoWSx1+/nEIbCP7WX9df8+4rZUGmjAriIYIdBkp1RaO0R7xvVJ79Fj
17AcxnY7WEf+/aGlikjiFvpRusyvp2sBW24tKurz20CG5IdWQSDFp/ybNknafLXT
0PupKrnSO963YqXtFyD+40UTLrSrfn/YiF6vsaozEuesLaIakexYvAjehloC+FMA
EQEAAYkCJQQYAQgADwUCWKvbhAIbDAUJACeNAAAKCRCb2DLMZpiBEKijD/9QinDK
B1aYTJmNWQxR4ei8ruksi9EFYN9qlmqQUW92uXa9xeQme3MkADT3WDHCRjXJ3faK
/pdbN4fHdIExJe6mfoSQ7ZPAFaEmmF3ka21uSCVcfl3ScTFFVPAWXyq383ZvUhQQ
FsDEyh7d8Uq2c6KZoQuL9acA1VZ1st6FFignagt3NX3CZF5gPPvUCj37MYW/ztPp
uWz0t8B0clD3oa5NLTvYktdzU9F/xkFE4gIenrxEMxmE3W0elz4JF8M8Yvpr82vx
3FjhofDaIFWqRWS4gDB0tHeh+3HrZdigZKebIrjwN+1bwCzPk/cq6mph0To7RIJU
DoVrk3DW9OoaD5Eh1TGwO+JxJAMzvjElC/K086mF+Bgu/2BvoW13mSTPV/vRchrr
1F6evDyDCyjYN8HA8ZEGyGrxoGhSN9+VR/z6MWYM2PBaFcg5xDmWBHnDZhdq9GZ0
XsshRwUXJRAzgNkpw/1P8ANOAcYdTXNsLvJLxKGRLYrbKS42uZH+jlbtGyUf6dtE
AsLU7wKy0o5EH6mHLqRkqW/S5of7DLljQbGBHkG7bAbTG2wN/nVrcnZhi/D4I5/d
klRcszBtvrmI7/wHhr/vglL8sxMLms5ZbEW8DozykF2GW2WD3WqQ2XKHbDk/+o4O
beijAefqyE+33rsNTd9+UUqYtnlGm59QLB0NEw==
=+/JP
-----END PGP PUBLIC KEY BLOCK-----

Namespace: dev-induction

**Comment by Abdul2** [comment]
there is a reference to be placed at bau page but suggested link is broken and hence request at this level

**Comment by Joseph-Irving** [comment]
it's not broken, it's because you're not part of our github org, you need someone on your team to ask for you to have access
