### ISSUE TITLE
Error on Pod - Failed to Mount - status 400

### ISSUE THREAD

**Issue by RoupeSahans-CG** [UKHomeOffice/hosting-platform#388]
Pod stuck on container creating.
Please describe the following pod to see error message and logs: opendjuserr3-aftc-sandpit-ha-ds2-0
The namespace is aftc-sandpit. 

I have tried multiple combinations of deleting pod, statefulset and pvc and the error still exists. 

Thanks & Regards
Roupe

**Comment by Joseph-Irving** [comment]
can you please raise this on the bau board https://github.com/UKHomeOffice/hosting-platform-bau
